apiVersion: v1
kind: Pod
metadata:
  name: nginx-service
  labels:
    app: nginx-web-service
    tier: front-end
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "50m"
          memory: "30M"