apiVersion: v1
kind: Service
metadata:
  name:  my-nginx-svc
spec:
  selector:
    app: nginx-web-service
    tier: front-end
  type:  NodePort
  ports:
  - name:  nginx-port
    port:  80
    targetPort:  80
    nodePort: 30003