apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis-app
    tier: front-end
spec:
  containers:
    - name: redis-app-c
      image: redis
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu : "30m"
          memory: "30M"