apiVersion: v1
kind: Service
metadata:
  name: result-web-app
spec:
  type: NodePort
  selector:
    app: result-app
    tier: front-end
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081