apiVersion: v1
kind: Service
metadata:
  name: voting-web-app
spec:
  type: NodePort
  selector:
    app: voting-app
    tier: front-end
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080